---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: 11.12.8
  encrypted_data_bag_secret_key_path: /var/chef/encrypted_data_bag_secret
  data_bags_path: /var/chef/data_bags
  environments_path: /var/chef/environments
  roles_path: /var/chef/roles

platforms:
  - name: ubuntu-12.04

suites:
  - name: default
    run_list:
      - role[stalltalk-app-server]
      - role[geotalk-app-server]
      - role[ccu-app-server]
    attributes:
      stalltalk:
        uwsgi:
          socket: 127.0.0.1:8080
          socket_type: tcp
    provisioner:
      solo_rb:
        environment: testing
