---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: 11.12.8
  encrypted_data_bag_secret_key_path: /var/chef/encrypted_data_bag_secret
  data_bags_path: /var/chef/data_bags

platforms:
  - name: ubuntu-12.04

suites:
  - name: default
    run_list:
      - recipe[apt]
      - recipe[stalltalk::default]
    attributes:
