---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: 11.12.8
  encrypted_data_bag_secret_key_path: /var/chef/encrypted_data_bag_secret
  data_bags_path: test/integration/default/data_bags
  environments_path: test/integration/default/environments
  roles_path: test/integration/default/roles

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - role[stalltalk-database]
      - role[stalltalk-app-server]
      - role[geotalk-app-server]
      - role[ccu-app-server]
    attributes:
      postgresql:
        password:
          postgres: test
    provisioner:
      solo_rb:
        environment: testing
