name             'stalltalk'
maintainer       'Lemuel Formacil'
maintainer_email 'lemuelf@sectioneleven.org'
license          'All rights reserved'
description      'Installs/Configures stalltalk'
long_description 'Installs/Configures stalltalk'
version          '0.2.3'

depends 'user'
depends 'ssh-util'
depends 'python'
depends 'git'
depends 'nginx'
depends 'nodejs'
